START_BASIC_HSM_STATE_TABLE
INIT ( DOMAIN, STATE_ROOT, STATE_A )
STATE ( DOMAIN, STATE_ROOT, STATE_B )
  INIT ( DOMAIN, STATE_B, STATE_B1 )
  STATE ( DOMAIN, STATE_B, STATE_B2 )
    INIT ( DOMAIN, STATE_B2, STATE_B2a )
    STATE ( DOMAIN, STATE_B2, STATE_B2b )
STATE (DOMAIN, STATE_ROOT, STATE_C )
END_BASIC_HSM_STATE_TABLE