START_BASIC_HSM_STATE_TABLE
INIT ( DOMAIN, STATE_ROOT, STATE_A )
STATE ( DOMAIN, STATE_ROOT, STATE_B )
  INIT ( DOMAIN, STATE_B, STATE_B1 )
  STATE ( DOMAIN, STATE_B, STATE_B2 )
    INIT ( DOMAIN, STATE_B2, STATE_B2a )
    STATE ( DOMAIN, STATE_B2, STATE_B2b )
STATE (DOMAIN, STATE_ROOT, STATE_C )
END_BASIC_HSM_STATE_TABLE

START_TRANSITION_TABLE( DOMAIN )
//  EXTERNAL_TRANSITION( hsm, from, to, by )
  EXTERNAL_TRANSITION( DOMAIN, STATE_A, STATE_B, HSM_EVENT_A )
  EXTERNAL_TRANSITION( DOMAIN, STATE_B, STATE_B2, HSM_EVENT_B )
END_TRANSITION_TABLE( DOMAIN )

START_INTERNAL_TRANSITION_TABLE( DOMAIN )
//  INTERNAL_TRANSITION( hsm, in, by, callback )
  INTERNAL_TRANSITION( DOMAIN, STATE_ROOT, HSM_EVENT_C, callback_A )
  INTERNAL_TRANSITION( DOMAIN, STATE_B, HSM_EVENT_D, callback_B )
END_INTERNAL_TRANSITION_TABLE( DOMAIN )

START_ACTION_TABLE( DOMAIN )
//  HSM_ACTION( hsm, in, entry_action, exit_action )
  HSM_ACTION( DOMAIN, STATE_ROOT, entry_A, NULL )
  HSM_ACTION( DOMAIN, STATE_A, NULL, NULL )
  HSM_ACTION( DOMAIN, STATE_A, NULL, exit_B )
  HSM_ACTION( DOMAIN, STATE_B, entry_C, exit_D )
END_ACTION_TABLE( DOMAIN )

START_EVENT_MAPPING( DOMAIN )
//  EVENT_MAP( hsm, msg_id, hsm_internal_event )
  EVENT_MAP( DOMAIN, MSGID_C, HSM_EVENT_C )
  TIMER_MAP( DOMAIN, TIMID_D, HSM_EVENT_D )
END_EVENT_MAPPING( DOMAIN )

